auto_sync = false
update_check = false
secrets_filter = true

search_mode = "fuzzy"
filter_mode = "global"
filter_mode_shell_up_key_binding = "workspace"
workspaces = true

style = "auto"
enter_accept = true
show_preview = true
show_tabs = false
command_chaining = true

history_filter = [
  "^cd",
  "^clear$",
  "^exit$",
  "^la",
  "^ll",
  "^ls",
  "^pwd$",
  "^y$", # yazi alias
  "^yazi",
  "^z ", # zoxide
  "^zi", # zoxide interactive
]

keymap_mode = "auto"
keymap_cursor = {
  emacs = "steady-block",
  vim_insert = "steady-bar",
  vim_normal = "steady-block"
}

[stats]
common_subcommands = [
  "adb",
  "adbe",
  "brew",
  "cargo",
  "docker",
  "git",
  "g", # git alias
  "git-spice",
  "gs", # git-spice alias
  "gh",
  "glab",
  "go",
  "gradle",
  "./gradlew",
  "gw", # Gradle wrapper with upfind
  "npm",
  "tmux",
]
common_prefix = ["sudo"]
ignored_commands = [
  "cd",
  "clear",
  "exit",
  "ls",
  "nvim",
  "pwd",
  "yazi",
  "y", # yazi alias
  "z",
]

[sync]
records = true

[tmux]
enabled = true
width = "80%"
height = "60%"
