matches:
  # Current ISO date
  - triggers: [":date", ":today"]
    replace: "{{now}}"
    vars:
      - name: now
        type: date
        params:
          format: "%F"

  # Current ISO date-time
  - triggers: [":datetime", ":now"]
    replace: "{{now}}"
    vars:
      - name: now
        type: date
        params:
          format: "%FT%T"

  - trigger: ":mdcode"
    force_mode: clipboard
    replace: |
      ```
      $|$
      ```

  - trigger: ":mdtable2"
    force_mode: clipboard
    replace: |
      |     |     |
      |-----|-----|
      | $|$    |     |

  - trigger: ":mdtable3"
    force_mode: clipboard
    replace: |
      |     |     |     |
      |-----|-----|-----|
      | $|$    |     |     |

  - trigger: ":mdtable4"
    force_mode: clipboard
    replace: |
      |     |     |     |     |
      |-----|-----|-----|-----|
      | $|$    |     |     |     |

  - trigger: ":aiprompt"
    force_mode: clipboard
    replace: |
      Task:
      - $|$

      Details/Constraints:
      - 

      Context files:
      - 

      Output:
      - 

      Verify:
      - 

      Pause after each step for review.
