matches:
  # Current ISO date
  - triggers: [":date", ":today"]
    replace: "{{now}}"
    vars:
      - name: now
        type: date
        params:
          format: "%F"

  # Current ISO date-time
  - triggers: [":datetime", ":now"]
    replace: "{{now}}"
    vars:
      - name: now
        type: date
        params:
          format: "%FT%T"

  - trigger: ":mdcode"
    force_mode: clipboard
    replace: |
      ```
      $|$
      ```

  - trigger: ":mdtable2"
    force_mode: clipboard
    replace: |
      |     |     |
      |-----|-----|
      | $|$    |     |

  - trigger: ":mdtable3"
    force_mode: clipboard
    replace: |
      |     |     |     |
      |-----|-----|-----|
      | $|$    |     |     |

  - trigger: ":mdtable4"
    force_mode: clipboard
    replace: |
      |     |     |     |     |
      |-----|-----|-----|-----|
      | $|$    |     |     |     |

  - trigger: ":aiprompt"
    force_mode: clipboard
    replace: |
      ## Task
      - $|$

      ## Context/Details/Constraints
      - 

      ## Output
      - 

      ## Verify
      -

      Start with a plan. Pause after each execution step to let me review.
