"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
command_timeout = 1000

format = """
$username\
$hostname\
$localip\
$shlvl\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$memory_usage\
$sudo\
$fill\
$cmd_duration\
$time\
$line_break\
$jobs\
$character"""

palette = "dracula"

[cmd_duration]
min_time = 0
show_milliseconds = true

[directory]
fish_style_pwd_dir_length = 1

[fill]
symbol = '─'
style = "white"

[git_commit]
only_detached = true
tag_disabled = false
tag_max_candidates = 0
tag_symbol = ' 🏷 '

[git_metrics]
disabled = false

[gcloud]
disabled = true

[localip]
disabled = false

[palettes.dracula]
background = "#282a36"
current_line = "#44475a"
foreground = "#f8f8f2"
comment = "#6272a4"
cyan = "#8be9fd"
green = "#50fa7b"
orange = "#ffb86c"
pink = "#ff79c6"
purple = "#bd93f9"
red = "#ff5555"
yellow = "#f1fa8c"

[shlvl]
disabled = false
threshold = 3 # baseline is 2 in tmux (Terminal -> Fish -> tmux -> Fish)

[status]
disabled = false

[sudo]
disabled = false

[time]
disabled = false

